### PR TITLE
Ubuntu linux tested

### PR DESCRIPTION
**Pull request by jankoslavic**

### CODE REVIEW

**Comment by jankoslavic** [comment]
@miha-pirnat @matmr @sbtlaarzc I propose to merge this to master and continue working on it.

**Comment by sbtlaarzc** [comment]
I agree.

**Comment by matmr** [comment]
Yes!

On Dec 6, 2017 09:02, "Blaž Starc" <notifications@github.com> wrote:

I agree.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/openmodal/OpenModal/pull/36#issuecomment-349564052>,
or mute
the thread

**Comment by miha-pirnat** [comment]
Do it :)

**Pull request merged**
